# Generated by Django 6.0.1 on 2026-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_systemprompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemprompt",
            name="prompts",
            field=models.TextField(max_length=10000),
        ),
    ]
